# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/iuke/Documents/ITBA/CRIPTO/TP-Cripto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/iuke/Documents/ITBA/CRIPTO/TP-Cripto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iuke/Documents/ITBA/CRIPTO/TP-Cripto/CMakeFiles /home/iuke/Documents/ITBA/CRIPTO/TP-Cripto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iuke/Documents/ITBA/CRIPTO/TP-Cripto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TP_Cripto

# Build rule for target.
TP_Cripto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TP_Cripto
.PHONY : TP_Cripto

# fast build rule for target.
TP_Cripto/fast:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/build
.PHONY : TP_Cripto/fast

src/args_parser.o: src/args_parser.c.o

.PHONY : src/args_parser.o

# target to build an object file
src/args_parser.c.o:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/args_parser.c.o
.PHONY : src/args_parser.c.o

src/args_parser.i: src/args_parser.c.i

.PHONY : src/args_parser.i

# target to preprocess a source file
src/args_parser.c.i:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/args_parser.c.i
.PHONY : src/args_parser.c.i

src/args_parser.s: src/args_parser.c.s

.PHONY : src/args_parser.s

# target to generate assembly for a file
src/args_parser.c.s:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/args_parser.c.s
.PHONY : src/args_parser.c.s

src/config.o: src/config.c.o

.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/config.c.s
.PHONY : src/config.c.s

src/distribution.o: src/distribution.c.o

.PHONY : src/distribution.o

# target to build an object file
src/distribution.c.o:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/distribution.c.o
.PHONY : src/distribution.c.o

src/distribution.i: src/distribution.c.i

.PHONY : src/distribution.i

# target to preprocess a source file
src/distribution.c.i:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/distribution.c.i
.PHONY : src/distribution.c.i

src/distribution.s: src/distribution.c.s

.PHONY : src/distribution.s

# target to generate assembly for a file
src/distribution.c.s:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/distribution.c.s
.PHONY : src/distribution.c.s

src/finding.o: src/finding.c.o

.PHONY : src/finding.o

# target to build an object file
src/finding.c.o:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/finding.c.o
.PHONY : src/finding.c.o

src/finding.i: src/finding.c.i

.PHONY : src/finding.i

# target to preprocess a source file
src/finding.c.i:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/finding.c.i
.PHONY : src/finding.c.i

src/finding.s: src/finding.c.s

.PHONY : src/finding.s

# target to generate assembly for a file
src/finding.c.s:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/finding.c.s
.PHONY : src/finding.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/TP_Cripto.dir/build.make CMakeFiles/TP_Cripto.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TP_Cripto"
	@echo "... src/args_parser.o"
	@echo "... src/args_parser.i"
	@echo "... src/args_parser.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/distribution.o"
	@echo "... src/distribution.i"
	@echo "... src/distribution.s"
	@echo "... src/finding.o"
	@echo "... src/finding.i"
	@echo "... src/finding.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

